// hw3/src/components/EditPlaylistForm.jsx
// src/components/EditPlaylistForm.jsx
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { usePlaylists } from '../hooks/usePlaylists';
import TrackItem from './TrackItem';
import { fetchAlbums } from '../utils/api';

const EditPlaylistForm = ({ playlist }) => {
  const [playlistData, setPlaylistData] = useState({
    name: '',
    isPublic: false,
    tracks: []
  });
  const [error, setError] = useState('');
  const [warning, setWarning] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [saveSuccess, setSaveSuccess] = useState(false);
  const [allTracks, setAllTracks] = useState([]);
  const { editPlaylist } = usePlaylists();
  const navigate = useNavigate();

  // Fetch all albums to get track information
  useEffect(() => {
    const loadAllTracks = async () => {
      try {
        const albums = await fetchAlbums();
        // Extract all tracks from all albums
        const tracks = albums.flatMap(album => 
          album.tracks.map(track => ({
            ...track,
            albumName: album.name,
            albumId: album.id,
            originalNumber: track.number || track.trackNumber || 0 // Store the original track number
          }))
        );
        setAllTracks(tracks);
      } catch (err) {
        console.error('Error loading tracks:', err);
        setWarning('Could not load complete track information. Some track details may be missing.');
      }
    };
    
    loadAllTracks();
  }, []);

  // Validate playlist prop
  useEffect(() => {
    if (!playlist || !playlist.id) {
      console.error('Invalid playlist provided to EditPlaylistForm:', playlist);
      setError('Invalid playlist data. Redirecting to home...');
      // Redirect after a short delay to show the error
      const timer = setTimeout(() => navigate('/'), 2000);
      return () => clearTimeout(timer);
    }
  }, [playlist, navigate]);

  // Format duration if it's in seconds
  const formatDuration = (duration) => {
    if (!duration) return '0:00';
    
    // If duration is already formatted as MM:SS, return it
    if (typeof duration === 'string' && duration.includes(':')) {
      return duration;
    }
    
    // If duration is a number (seconds), format it as MM:SS
    if (typeof duration === 'number' || !isNaN(Number(duration))) {
      const totalSeconds = Number(duration);
      const minutes = Math.floor(totalSeconds / 60);
      const seconds = Math.floor(totalSeconds % 60);
      return `${minutes}:${seconds.toString().padStart(2, '0')}`;
    }
    
    return duration || '0:00';
  };

  // Helper function to assign sequential playlist numbers to tracks
  const assignSequentialNumbers = (tracks) => {
    return tracks.map((track, index) => ({
      ...track,
      playlistNumber: index + 1, // Sequential number starting from 1
      // Keep the original number from the album
      originalNumber: track.originalNumber || track.number || track.trackNumber || 0
    }));
  };

  // Update form data when playlist prop changes
  useEffect(() => {
    if (playlist) {
      // Ensure tracks are properly formatted for display
      let formattedTracks = (playlist.tracks || []).map(track => {
        // If track is already an object with all required fields, use it
        if (typeof track === 'object' && track.id) {
          // Find complete track info from allTracks if available
          const completeTrack = allTracks.find(t => t.id === track.id || t._id === track.id);
          
          if (completeTrack) {
            return {
              ...completeTrack,
              id: track.id || track._id,
              _id: track._id || track.id,
              // Store the original album track number
              originalNumber: completeTrack.number || completeTrack.trackNumber || track.number || track.trackNumber || 0
            };
          }
          
          // Ensure it has all required display fields
          return {
            ...track,
            title: track.title || track.name || `Track ${track.id}`,
            name: track.name || track.title || `Track ${track.id}`,
            duration: formatDuration(track.duration),
            originalNumber: track.number || track.trackNumber || 0,
            id: track.id || track._id,
            _id: track._id || track.id
          };
        }
        
        // If track is just an ID string, convert it to an object
        // Try to find complete track info from allTracks
        const completeTrack = allTracks.find(t => t.id === track || t._id === track);
        
        if (completeTrack) {
          return {
            ...completeTrack,
            id: track,
            _id: track,
            originalNumber: completeTrack.number || completeTrack.trackNumber || 0
          };
        }
        
        return {
          id: track,
          _id: track,
          title: `Track ${track}`,
          name: `Track ${track}`,
          originalNumber: 0,
          duration: '0:00'
        };
      });

      // Assign sequential numbers to tracks in the playlist
      formattedTracks = assignSequentialNumbers(formattedTracks);

      // Log the isPublic value from the playlist prop
      console.log('Initializing form with isPublic value:', playlist.isPublic);
      
      setPlaylistData({
        name: playlist.name || '',
        isPublic: playlist.isPublic === true, // Ensure boolean value
        tracks: formattedTracks,
        id: playlist.id,
        _id: playlist._id || playlist.id
      });
    }
  }, [playlist, allTracks]);

  const handleChange = (e) => {
    const { name, value, type, checked } = e.target;
    const newValue = type === 'checkbox' ? checked : value;
    
    console.log(`Updating ${name} to:`, newValue, 'type:', type);
    
    setPlaylistData(prev => ({
      ...prev,
      [name]: newValue
    }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    // Clear previous messages
    setError('');
    setWarning('');
    setSaveSuccess(false);
    
    if (!playlistData.name.trim()) {
      setError('Playlist name is required');
      return;
    }
    
    if (!playlist || !playlist.id) {
      setError('Cannot update playlist: Invalid ID');
      return;
    }
    
    setIsSubmitting(true);
    
    try {
      // Explicitly log the isPublic property to verify it's being included
      console.log('Submitting updated playlist with isPublic:', playlistData.isPublic);
      console.log('Submitting updated playlist:', playlistData);
      
      // Ensure the playlist data has consistent ID fields
      const normalizedData = { 
        ...playlistData,
        id: playlist.id,
        _id: playlist._id || playlist.id,
        isPublic: playlistData.isPublic // Explicitly include isPublic property
      };
      
      // Ensure tracks have proper format for the backend
      normalizedData.tracks = normalizedData.tracks.map((track, index) => {
        // If track is already an object, ensure it has an id and preserve all track details
        if (typeof track === 'object') {
          // Find complete track info from allTracks if available
          const completeTrack = allTracks.find(t => t.id === track.id || t._id === track.id);
          
          if (completeTrack) {
            return {
              ...completeTrack,
              id: track.id || track._id || `track-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
              _id: track._id || track.id || `track-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
              title: completeTrack.title || completeTrack.name || track.title || track.name || `Track ${track.id || track._id}`,
              name: completeTrack.name || completeTrack.title || track.name || track.title || `Track ${track.id || track._id}`,
              duration: completeTrack.duration || track.duration || '0:00',
              number: index + 1, // Sequential number based on position
              originalNumber: completeTrack.originalNumber || completeTrack.number || completeTrack.trackNumber || track.originalNumber || track.number || 0,
              playlistNumber: index + 1 // Explicitly track the playlist position
            };
          }
          
          return {
            ...track,
            id: track.id || track._id || `track-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
            _id: track._id || track.id || `track-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
            title: track.title || track.name || `Track ${track.id || track._id}`,
            name: track.name || track.title || `Track ${track.id || track._id}`,
            duration: formatDuration(track.duration),
            number: index + 1, // Sequential number based on position
            originalNumber: track.originalNumber || track.number || track.trackNumber || 0,
            playlistNumber: index + 1 // Explicitly track the playlist position
          };
        }
        
        // If track is just an ID string, convert it to an object
        // Try to find complete track info from allTracks
        const completeTrack = allTracks.find(t => t.id === track || t._id === track);
        
        if (completeTrack) {
          return {
            ...completeTrack,
            id: track,
            _id: track,
            number: index + 1, // Sequential number based on position
            originalNumber: completeTrack.number || completeTrack.trackNumber || 0,
            playlistNumber: index + 1 // Explicitly track the playlist position
          };
        }
        
        return {
          id: track,
          _id: track,
          title: `Track ${track}`,
          name: `Track ${track}`,
          number: index + 1, // Sequential number based on position
          originalNumber: 0,
          playlistNumber: index + 1, // Explicitly track the playlist position
          duration: '0:00'
        };
      });
      
      // Save a local copy for optimistic updates
      const localCopy = JSON.stringify(normalizedData);
      localStorage.setItem(`playlist_backup_${playlist.id}`, localCopy);
      
      const updatedPlaylist = await editPlaylist(playlist.id, normalizedData);
      console.log('Playlist updated successfully:', updatedPlaylist);
      
      setSaveSuccess(true);
      
      // Navigate after a short delay to show the success message
      setTimeout(() => navigate('/'), 1500);
    } catch (err) {
      console.error('Error updating playlist:', err);
      setError(`Failed to update playlist: ${err.message || 'Unknown error'}`);
      setIsSubmitting(false);
    }
  };

  const removeTrack = (trackId) => {
    setPlaylistData(prev => {
      // Remove the track
      const updatedTracks = prev.tracks.filter(track => track.id !== trackId);
      // Re-assign sequential numbers
      return {
        ...prev,
        tracks: assignSequentialNumbers(updatedTracks)
      };
    });
  };

  const moveTrack = (trackId, direction) => {
    const trackIndex = playlistData.tracks.findIndex(track => track.id === trackId);
    if (
      (direction === 'up' && trackIndex === 0) || 
      (direction === 'down' && trackIndex === playlistData.tracks.length - 1)
    ) {
      return;
    }

    const newTracks = [...playlistData.tracks];
    const targetIndex = direction === 'up' ? trackIndex - 1 : trackIndex + 1;
    
    // Swap the tracks
    [newTracks[trackIndex], newTracks[targetIndex]] = 
    [newTracks[targetIndex], newTracks[trackIndex]];
    
    // Re-assign sequential numbers
    setPlaylistData(prev => ({
      ...prev,
      tracks: assignSequentialNumbers(newTracks)
    }));
  };

  // Modified TrackItem component to display playlistNumber in playlist view
  const PlaylistTrackItem = ({ track, index }) => {
    return (
      <div className="track-item">
        <span className="track-number">{index + 1}.</span>
        <span className="track-title">{track.title || track.name}</span>
        <span className="track-duration">{track.duration}</span>
        {track.originalNumber > 0 }
      </div>
    );
  };

  // If there's a critical error, just show the error message
  if (error && !playlist?.id) {
    return (
      <div className="edit-playlist-form-container">
        <div className="error">{error}</div>
      </div>
    );
  }

  return (
    <div className="edit-playlist-form-container">
      <form onSubmit={handleSubmit} className="playlist-form">
        {error && <div className="error">{error}</div>}
        {warning && <div className="warning">{warning}</div>}
        {saveSuccess && <div className="success">Playlist saved successfully!</div>}
        
        <div className="form-group">
          <label htmlFor="name">Playlist Name</label>
          <input
            type="text"
            id="name"
            name="name"
            value={playlistData.name}
            onChange={handleChange}
            required
            readOnly
          />
        </div>
        
        <div className="form-group checkbox">
          <label>
            <input
              type="checkbox"
              name="isPublic"
              checked={playlistData.isPublic}
              onChange={handleChange}
            />
            Make this playlist public
          </label>
        </div>
        
        <div className="tracks-container">
          <h3>Tracks in this Playlist</h3>
          {playlistData.tracks.length === 0 ? (
            <p>No tracks in this playlist. Add tracks from the albums below.</p>
          ) : (
            <div className="tracks-list">
              {playlistData.tracks.map((track, index) => (
                <div key={track.id} className="playlist-track-item">
                  <PlaylistTrackItem track={track} index={index} />
                  <div className="track-actions">
                    <button 
                      type="button" 
                      onClick={() => moveTrack(track.id, 'up')}
                      disabled={index === 0}
                    >
                      ↑
                    </button>
                    <button 
                      type="button" 
                      onClick={() => moveTrack(track.id, 'down')}
                      disabled={index === playlistData.tracks.length - 1}
                    >
                      ↓
                    </button>
                    <button 
                      type="button" 
                      onClick={() => removeTrack(track.id)}
                      className="remove-track"
                    >
                      Remove
                    </button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
        
        <div className="form-actions">
          <button type="submit" disabled={isSubmitting || !playlist?.id}>
            {isSubmitting ? 'Saving...' : 'Save Changes'}
          </button>
          <button 
            type="button" 
            onClick={() => navigate('/')}
            disabled={isSubmitting}
          >
            Back
          </button>
          
        </div>
        <p>Note:</p>
        <p>Tracks get automatically added to playlist no need to save, for everything else please click on Save Changes</p>
      </form>
    </div>
  );
};

export default EditPlaylistForm;

// research/src/app/components/edit-playlist-form/edit-playlist-form.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { ApiService } from '../../services/api.service';
import { Playlist, Track } from '../../models/playlist.model';
import { Album } from '../../models/album.model';
import { LoadingSpinnerComponent } from '../loading-spinner/loading-spinner.component';
import { Observable, of } from 'rxjs';
import { switchMap, take, catchError } from 'rxjs/operators';

@Component({
  selector: 'app-edit-playlist-form',
  standalone: true,
  imports: [CommonModule, FormsModule, ReactiveFormsModule, RouterModule, LoadingSpinnerComponent],
  templateUrl: './edit-playlist-form.component.html',
  styleUrls: ['./edit-playlist-form.component.css']
})
export class EditPlaylistFormComponent implements OnInit {
  @Input() playlist!: Playlist;

  playlistForm!: FormGroup;
  allTracks: Track[] = [];
  filteredTracks: Track[] = [];
  albums: Album[] = [];
  selectedAlbumId = '';
  loading = false;
  loadingAlbums = false;
  error: string | null = null;
  warning: string | null = null;
  saveSuccess = false;

  constructor(
    private fb: FormBuilder,
    private apiService: ApiService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.initForm();
    this.loadAllTracks();
  }

  private initForm(): void {
    // Format the tracks first to ensure they're all Track objects
    this.formatPlaylistTracks();
    
    this.playlistForm = this.fb.group({
      name: [{value: this.playlist.name, disabled: true}, [Validators.required, Validators.minLength(3)]],
      isPublic: [this.playlist.isPublic],
      tracks: [this.playlist.tracks || []]
    });
    
    console.log('Form initialized with tracks:', this.playlistForm.value.tracks);
  }
  
  private formatPlaylistTracks(): void {
    // Ensure all playlist tracks have the required properties
    if (this.playlist && this.playlist.tracks) {
      console.log('Original playlist tracks:', this.playlist.tracks);
      
      // Handle the case where playlist tracks are just IDs (strings)
      const formattedTracks = this.playlist.tracks.map((trackData, index) => {
        // Check if trackData is just a string (ID)
        if (typeof trackData === 'string' || typeof trackData === 'number') {
          const trackId = String(trackData);
          console.log(`Looking for track with ID: ${trackId}`);
          
          // Find the track in allTracks by ID
          const matchingTrack = this.allTracks.find(t => 
            t.id === trackId || 
            t.id === `${trackId}` || 
            t.id.endsWith(`-${trackId}`)
          );
          
          if (matchingTrack) {
            console.log(`Found matching track for ID ${trackId}:`, matchingTrack);
            return {
              ...matchingTrack,
              playlistNumber: index + 1
            };
          } else {
            console.log(`No matching track found for ID ${trackId}`);
            // Create a placeholder track
            return {
              id: trackId,
              title: `Track ${index + 1}`,
              artist: 'Unknown Artist',
              album: 'Unknown Album',
              duration: 0,
              albumId: '',
              number: index + 1,
              originalNumber: index + 1
            } as Track;
          }
        }
        
        // If trackData is an object, handle it as before
        const track = trackData as Track;
        
        // Try to find a matching track in allTracks by ID
        let matchingTrack = this.allTracks.find(t => t.id === track.id);
        
        // If no match by ID, try to match by title
        if (!matchingTrack && track.title) {
          matchingTrack = this.allTracks.find(t => 
            t.title.toLowerCase() === track.title.toLowerCase()
          );
        }
        
        if (matchingTrack) {
          // Use the matching track's data but keep the playlist track's ID
          return {
            ...matchingTrack,
            id: track.id || matchingTrack.id,
            playlistNumber: index + 1
          };
        }
        
        // If no match found, use the original track with defaults for missing properties
        return {
          id: track.id || `playlist-track-${index}`,
          title: track.title || 'Unknown Track',
          artist: track.artist || 'Unknown Artist',
          album: track.album || 'Unknown Album',
          duration: track.duration || 0,
          albumId: track.albumId || '',
          number: index + 1,
          originalNumber: track.originalNumber || index + 1
        } as Track;
      });
      
      this.playlist.tracks = formattedTracks;
      console.log('Formatted playlist tracks:', this.playlist.tracks);
      
      // If the form is already initialized, update it
      if (this.playlistForm) {
        this.playlistForm.patchValue({
          tracks: this.playlist.tracks
        });
        console.log('Updated form with formatted tracks:', this.playlistForm.value.tracks);
      }
    }
  }

  private loadAllTracks(): void {
    this.loadingAlbums = true;
    this.apiService.getAlbums().subscribe({
      next: (albums) => {
        console.log('Albums loaded in component:', albums);
        this.albums = albums;
        
        // Extract all tracks from all albums
        this.allTracks = albums.flatMap(album => {
          // Check if album has tracks property and it's an array
          if (!album.tracks || !Array.isArray(album.tracks)) {
            console.warn(`Album ${album.id} has no tracks or tracks is not an array`);
            return [];
          }
          
          return album.tracks.map((track, index) => {
            // Get the primaryArtist from the track if available
            const trackWithArtist = track as { primaryArtist?: string };
            const primaryArtist = trackWithArtist.primaryArtist || album.artist || '';
            
            // Generate a consistent ID for the track
            // Format: albumId-trackNumber (e.g., "0-1", "1-3")
            const trackNumber = track.number || track.trackNumber || (index + 1);
            const trackId = `${album.id}-${trackNumber}`;
            
            // Create a complete Track object with all required properties
            const completeTrack: Track = {
              id: trackId, // Use our consistent ID format
              title: track.title || '',
              duration: typeof track.duration === 'string' ? this.parseDuration(track.duration) : (track.duration || 0),
              artist: primaryArtist,
              album: album.title || '',
              albumId: album.id,
              albumName: album.title || '',
              // Set optional properties with default values
              number: trackNumber,
              originalNumber: trackNumber
            };
            
            console.log(`Created track with ID ${trackId}:`, completeTrack);
            return completeTrack;
          });
        });
        
        // Initialize filtered tracks with all tracks
        this.filteredTracks = [...this.allTracks];
        
        console.log('All tracks loaded:', this.allTracks);
        this.loadingAlbums = false;
        
        // Now that we have all tracks, format the playlist tracks
        this.formatPlaylistTracks();
      },
      error: (err) => {
        console.error('Error loading tracks:', err);
        this.warning = 'Could not load complete track information. Some track details may be missing.';
        this.loadingAlbums = false;
      }
    });
  }
  
  onAlbumSelect(event: Event): void {
    const selectElement = event.target as HTMLSelectElement;
    const albumId = selectElement.value;
    
    this.selectedAlbumId = albumId;
    
    if (!albumId) {
      // If no album is selected, show all tracks
      this.filteredTracks = [...this.allTracks];
    } else {
      // Filter tracks by the selected album ID
      this.filteredTracks = this.allTracks.filter(track => track.albumId === albumId);
    }
    
    console.log(`Filtered tracks for album ${albumId}:`, this.filteredTracks);
  }
  
  // Helper method to parse duration strings like "4:35" to seconds
  private parseDuration(durationStr: string): number {
    if (!durationStr) return 0;
    
    const parts = durationStr.split(':');
    if (parts.length === 2) {
      const minutes = parseInt(parts[0], 10);
      const seconds = parseInt(parts[1], 10);
      return (minutes * 60) + seconds;
    }
    
    return 0;
  }

  formatDuration(duration: number | string): string {
    if (!duration) return '0:00';
    
    // If duration is already formatted as MM:SS, return it
    if (typeof duration === 'string' && duration.includes(':')) {
      return duration;
    }
    
    // If duration is a number (seconds), format it as MM:SS
    if (typeof duration === 'number' || !isNaN(Number(duration))) {
      const totalSeconds = Number(duration);
      const minutes = Math.floor(totalSeconds / 60);
      const seconds = Math.floor(totalSeconds % 60);
      return `${minutes}:${seconds.toString().padStart(2, '0')}`;
    }
    
    return '0:00';
  }

  removeTrack(trackId: string): void {
    // Update the playlist tracks
    this.playlist.tracks = this.playlist.tracks.filter(track => track.id !== trackId);
    
    // Update the form value
    this.playlistForm.patchValue({
      tracks: this.playlist.tracks
    });
    
    console.log('Track removed, updated tracks:', this.playlistForm.value.tracks);
  }

  moveTrack(trackId: string, direction: 'up' | 'down'): void {
    const currentIndex = this.playlist.tracks.findIndex(track => track.id === trackId);
    if (currentIndex === -1) return;

    const newIndex = direction === 'up' ? currentIndex - 1 : currentIndex + 1;
    if (newIndex < 0 || newIndex >= this.playlist.tracks.length) return;

    // Swap tracks
    const tracks = [...this.playlist.tracks];
    [tracks[currentIndex], tracks[newIndex]] = [tracks[newIndex], tracks[currentIndex]];
    this.playlist.tracks = tracks;
    
    // Update the form value
    this.playlistForm.patchValue({
      tracks: this.playlist.tracks
    });
    
    console.log('Track moved, updated tracks:', this.playlistForm.value.tracks);
  }

  addTrack(track: Track): void {
    // Check if track already exists in playlist
    if (this.playlist.tracks.some(t => t.id === track.id)) {
      this.error = 'This track is already in the playlist';
      return;
    }

    // Add track to playlist
    this.playlist.tracks.push(track);
    
    // Update the form value
    this.playlistForm.patchValue({
      tracks: this.playlist.tracks
    });
    
    console.log('Track added, updated tracks:', this.playlistForm.value.tracks);
  }

  onSubmit(): void {
    if (this.playlistForm.invalid) {
      return;
    }

    this.loading = true;
    this.error = null;
    this.warning = null;
    this.saveSuccess = false;

    // Get form values, including disabled controls
    const formValues = {
      ...this.playlistForm.getRawValue()
    };
    
    const playlistId = this.playlist.id;
    
    console.log('Form values:', formValues);
    console.log('Current playlist:', this.playlist);
    
    // 2. Update isPublic if changed
    let updateOperation: Observable<Playlist>;
    if (formValues.isPublic !== this.playlist.isPublic) {
      console.log(`Updating isPublic from ${this.playlist.isPublic} to ${formValues.isPublic}`);
      updateOperation = this.apiService.updatePlaylist(playlistId, { isPublic: formValues.isPublic });
    } else {
      // If isPublic hasn't changed, just get the current playlist
      updateOperation = this.apiService.getPlaylist(playlistId);
    }
    
    // Start with updating isPublic or getting the current playlist
    updateOperation.pipe(
      // Then handle track changes
      switchMap(updatedPlaylist => {
        // 3. Handle track changes
        const currentTracks: Track[] = formValues.tracks || [];
        
        // Get the server's current tracks
        const serverTracks = updatedPlaylist.tracks || [];
        
        // Convert server tracks to Track objects if they're strings
        const serverTrackIds = serverTracks.map(track => 
          typeof track === 'string' ? track : track.id
        );
        
        console.log('Current tracks from form:', currentTracks);
        console.log('Server track IDs:', serverTrackIds);
        
        // Get track IDs for comparison
        const currentTrackIds = currentTracks.map(track => track.id);
        
        console.log('Current track IDs:', currentTrackIds);
        
        // Find tracks to add (in current but not in server)
        const tracksToAdd = currentTracks.filter(track => 
          !serverTrackIds.includes(track.id)
        );
        
        // Find tracks to remove (in server but not in current)
        const tracksToRemove = serverTrackIds.filter(trackId => 
          !currentTrackIds.includes(trackId)
        );
        
        console.log('Tracks to add:', tracksToAdd);
        console.log('Tracks to remove:', tracksToRemove);
        
        // Process track operations sequentially
        let trackOperation: Observable<unknown> = of(updatedPlaylist);
        
        // Add new tracks one by one
        for (const track of tracksToAdd) {
          console.log(`Adding track ${track.id} to playlist ${playlistId}`);
          trackOperation = trackOperation.pipe(
            switchMap(() => this.apiService.addTrackToPlaylist(playlistId, track.id).pipe(
              catchError(error => {
                console.error(`Error adding track ${track.id}:`, error);
                return of(null);
              })
            ))
          );
        }
        
        // Remove tracks one by one
        for (const trackId of tracksToRemove) {
          console.log(`Removing track ${trackId} from playlist ${playlistId}`);
          trackOperation = trackOperation.pipe(
            switchMap(() => this.apiService.removeTrackFromPlaylist(playlistId, trackId).pipe(
              catchError(error => {
                console.error(`Error removing track ${trackId}:`, error);
                return of(null);
              })
            ))
          );
        }
        
        // After all track operations, get the updated playlist
        return trackOperation.pipe(
          switchMap(() => {
            console.log('All track operations completed');
            return this.apiService.getPlaylist(playlistId);
          })
        );
      }),
      // Then handle track reordering
      switchMap(updatedPlaylist => {
        console.log('Handling track reordering');
        
        // Get the current tracks from the form
        const currentTracks: Track[] = formValues.tracks || [];
        
        // If there are no tracks, return the playlist
        if (currentTracks.length === 0) {
          return of(updatedPlaylist);
        }
        
        // Process reordering operations sequentially
        let reorderOperation: Observable<unknown> = of(updatedPlaylist);
        
        // Move tracks to their correct positions one by one
        currentTracks.forEach((track, index) => {
          console.log(`Moving track ${track.id} to position ${index}`);
          reorderOperation = reorderOperation.pipe(
            switchMap(() => this.apiService.moveTrackInPlaylist(playlistId, track.id, index).pipe(
              catchError(error => {
                console.error(`Error moving track ${track.id} to position ${index}:`, error);
                return of(null);
              })
            ))
          );
        });
        
        // After all reordering operations, get the updated playlist
        return reorderOperation.pipe(
          switchMap(() => {
            console.log('All reordering operations completed');
            return this.apiService.getPlaylist(playlistId);
          })
        );
      }),
      take(1)
    ).subscribe({
      next: (updatedPlaylist) => {
        console.log('Playlist updated successfully:', updatedPlaylist);
        this.loading = false;
        this.saveSuccess = true;
        
        // Update the local playlist object with the server response
        this.playlist = updatedPlaylist;
        
        // Reset the form with the updated playlist data
        this.initForm();
      },
      error: (err) => {
        console.error('Error updating playlist:', err);
        this.loading = false;
        this.error = 'Failed to update playlist. Please try again.';
      }
    });
  }

  deletePlaylist(): void {
    if (!confirm('Are you sure you want to delete this playlist?')) {
      return;
    }

    this.loading = true;
    this.apiService.deletePlaylist(this.playlist.id).subscribe({
      next: () => {
        this.loading = false;
        this.router.navigate(['/']);
      },
      error: (err) => {
        console.error('Error deleting playlist:', err);
        this.error = 'Failed to delete playlist. Please try again.';
        this.loading = false;
      }
    });
  }

  // Form getters for template access
  get name() { return this.playlistForm.get('name'); }

  isTrackInPlaylist(trackId: string): boolean {
    return this.playlist.tracks.some(track => {
      // Handle both track objects and track IDs
      if (typeof track === 'string') {
        return track === trackId;
      }
      return track.id === trackId;
    });
  }
}

<div class="form-container">
  @if (loading) {
    <app-loading-spinner></app-loading-spinner>
  } @else {
    @if (error) {
      <div class="error-message">{{ error }}</div>
    }
    @if (warning) {
      <div class="warning-message">{{ warning }}</div>
    }
    @if (saveSuccess) {
      <div class="success-message">Playlist updated successfully!</div>
    }

    <form [formGroup]="playlistForm" (ngSubmit)="onSubmit()">
      <div class="form-group">
        <label for="name">Playlist Name</label>
        <input
          type="text"
          id="name"
          formControlName="name"
          placeholder="Enter playlist name"
          [class.invalid]="name?.invalid && (name?.dirty || name?.touched)"
        >
        @if (name?.invalid && (name?.dirty || name?.touched)) {
          <div class="error-text">
            @if (name?.errors?.['required']) {
              Name is required.
            }
            @if (name?.errors?.['minlength']) {
              Name must be at least 3 characters.
            }
          </div>
        }
      </div>

      <div class="form-group">
        <label class="checkbox-label">
          <input type="checkbox" formControlName="isPublic">
          Make playlist public
        </label>
      </div>

      <div class="tracks-section">
        <h3>Tracks</h3>
        @if (loadingAlbums) {
          <app-loading-spinner></app-loading-spinner>
        } @else {
          <div class="track-list">
            @for (track of playlist.tracks; track track.id + '-' + $index; let i = $index) {
              <div class="track-item">
                <div class="track-number">{{ i + 1 }}</div>
                <div class="track-info">
                  <div class="track-title">{{ track.title }}</div>
                  <div class="track-meta">
                    {{ track.artist }} - {{ track.album }}
                  </div>
                  <div class="track-duration">{{ formatDuration(track.duration) }}</div>
                </div>
                <div class="track-actions">
                  @if (i > 0) {
                    <button type="button" class="move-btn" (click)="moveTrack(track.id, 'up')" title="Move Up">↑</button>
                  }
                  @if (i < playlist.tracks.length - 1) {
                    <button type="button" class="move-btn" (click)="moveTrack(track.id, 'down')" title="Move Down">↓</button>
                  }
                  <button type="button" class="remove-btn" (click)="removeTrack(track.id)" title="Remove">×</button>
                </div>
              </div>
            }
          </div>

          <div class="add-tracks-section">
            <h4>Add Tracks</h4>
            
            <div class="album-filter">
              <label for="album-select">Filter by Album:</label>
              <select 
                id="album-select" 
                (change)="onAlbumSelect($event)"
                class="album-select"
              >
                <option value="">All Albums</option>
                @for (album of albums; track album.id) {
                  <option [value]="album.id">{{ album.title }} - {{ album.artist }}</option>
                }
              </select>
            </div>
            
            <div class="available-tracks">
              @if (filteredTracks.length === 0) {
                <div class="no-tracks-message">No tracks available for this album</div>
              } @else {
                @for (track of filteredTracks; track track.id + '-' + $index; let i = $index) {
                  <div class="available-track-item">
                    <div class="track-info">
                      <div class="track-title">{{ track.title }}</div>
                      <div class="track-meta">
                        {{ track.artist }} - {{ track.albumName }}
                      </div>
                    </div>
                    @if (isTrackInPlaylist(track.id)) {
                      <span class="track-added">Added</span>
                    } @else {
                      <button type="button" class="add-btn" (click)="addTrack(track)">Add</button>
                    }
                  </div>
                }
              }
            </div>
          </div>
        }
      </div>

      <div class="form-actions">
        <div class="right-actions">
          <button type="submit" class="submit-btn" [disabled]="playlistForm.invalid || loading">
            Save Changes
          </button>
          <a routerLink="/" class="cancel-btn">Cancel</a>
        </div>
      </div>
    </form>
  }
</div>
