// hw3/src/components/Header.jsx
// src/components/Header.jsx
import { useContext } from 'react';
import { Link } from 'react-router-dom';
import { AuthContext } from '../context/AuthContext';

const Header = () => {
  const { isAuthenticated, logout, user } = useContext(AuthContext);

  const handleLogout = () => {
    logout();
    // Auth0 will handle the redirect
  };

  return (
    <header className="header">
      <div className="logo">
        <Link to="/">Pandify</Link>
      </div>
      <nav>
        {isAuthenticated ? (
          <div className="nav-links">
            {user && (
              <span className="user-info">
                {user.picture && (
                  <img 
                    src={user.picture} 
                    alt={user.name || 'User'} 
                    className="user-avatar"
                  />
                )}
                <span>Welcome, {user.name || user.email || 'User'}</span>
              </span>
            )}
            <button onClick={handleLogout} className="logout-btn">Logout</button>
          </div>
        ) : (
          <Link to="/login">Login</Link>
        )}
      </nav>
    </header>
  );
};

export default Header;

// research/src/app/components/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {
  isAuthenticated = false;
  user: any = null;

  constructor(private authService: AuthService) {}

  ngOnInit(): void {
    this.authService.isAuthenticated().subscribe(isAuthenticated => {
      this.isAuthenticated = isAuthenticated;
    });

    this.authService.getUser().subscribe(user => {
      this.user = user;
    });
  }

  login(): void {
    this.authService.login();
  }

  logout(): void {
    this.authService.logout();
  }
}

<header class="app-header">
  <div class="logo">
    <a routerLink="/">Pandify</a>
  </div>
  <nav>
    <ul>
      @if (isAuthenticated) {
        <li>
          <button (click)="logout()" class="logout-btn">Logout</button>
        </li>
        @if (user) {
          <li class="user-info">
            <img [src]="user.picture" alt="User avatar" class="avatar" *ngIf="user.picture">
            <span>{{ user.name }}</span>
          </li>
        }
      } @else {
        <li>
          <button (click)="login()" class="login-btn">Login</button>
        </li>
      }
    </ul>
  </nav>
</header>
