// hw3/src/components/PlaylistItem.jsx
// src/components/PlaylistItem.jsx
import { Link } from 'react-router-dom';

const PlaylistItem = ({ playlist }) => {
  return (
    <div className="playlist-item">
      <div className="playlist-info">
        <h3>{playlist.name}</h3>
        <p className="playlist-status">
          {playlist.isPublic ? 'Public' : 'Private'}
        </p>
      </div>
      <div className="playlist-actions">
        <Link to={`/playlists/${playlist.id}/edit`} className="edit-playlist-btn">
          Edit Playlist
        </Link>
      </div>
    </div>
  );
};

export default PlaylistItem;

// research/src/app/components/playlist-item/playlist-item.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { Playlist } from '../../models/playlist.model';

@Component({
  selector: 'app-playlist-item',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './playlist-item.component.html',
  styleUrls: ['./playlist-item.component.css']
})
export class PlaylistItemComponent {
  @Input() playlist!: Playlist;

  getTrackCount(): string {
    const count = this.playlist.tracks.length;
    return count === 1 ? '1 track' : `${count} tracks`;
  }
}

<div class="playlist-item">
  <div class="playlist-info">
    <h3>{{ playlist.name }}</h3>
    <p class="playlist-status">
      {{ playlist.isPublic ? 'Public' : 'Private' }}
    </p>
    <p class="playlist-tracks">{{ getTrackCount() }}</p>
  </div>
  <div class="playlist-actions">
    <a class="edit-playlist-btn" [routerLink]="['/playlists', playlist.id, 'edit']">
      Edit Playlist
    </a>
  </div>
</div>
