// research/src/app/components/new-playlist-form/new-playlist-form.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { ApiService } from '../../services/api.service';
import { LoadingSpinnerComponent } from '../loading-spinner/loading-spinner.component';

@Component({
  selector: 'app-new-playlist-form',
  standalone: true,
  imports: [CommonModule, FormsModule, ReactiveFormsModule, LoadingSpinnerComponent],
  templateUrl: './new-playlist-form.component.html',
  styleUrls: ['./new-playlist-form.component.css']
})
export class NewPlaylistFormComponent implements OnInit {
  playlistForm!: FormGroup;
  loading = false;
  error: string | null = null;

  constructor(
    private fb: FormBuilder,
    private apiService: ApiService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.initForm();
  }

  initForm(): void {
    this.playlistForm = this.fb.group({
      name: ['', [Validators.required, Validators.minLength(3)]],
      isPublic: [false]
    });
  }

  onSubmit(): void {
    if (this.playlistForm.invalid) {
      return;
    }

    this.loading = true;
    this.error = null;

    const newPlaylist = {
      name: this.playlistForm.get('name')?.value?.trim(),
      isPublic: this.playlistForm.get('isPublic')?.value || false
    };

    console.log('Creating playlist:', newPlaylist);

    this.apiService.createPlaylist(newPlaylist).subscribe({
      next: (playlist) => {
        console.log('Playlist created successfully:', playlist);
        this.loading = false;
        this.router.navigate(['/']);
      },
      error: (err) => {
        console.error('Error creating playlist:', err);
        this.loading = false;
        this.error = err.message || 'Failed to create playlist. Please try again.';
      }
    });
  }

  // Form getters for template access
  get name() { return this.playlistForm.get('name'); }
}

<div class="form-container">
  @if (loading) {
    <app-loading-spinner></app-loading-spinner>
  } @else {
    @if (error) {
      <div class="error-message">{{ error }}</div>
    }

    <form [formGroup]="playlistForm" (ngSubmit)="onSubmit()">
      <div class="form-group">
        <label for="name">Playlist Name</label>
        <input
          type="text"
          id="name"
          formControlName="name"
          placeholder="Enter playlist name"
          [class.invalid]="name?.invalid && (name?.dirty || name?.touched)"
        >
        @if (name?.invalid && (name?.dirty || name?.touched)) {
          <div class="error-text">
            @if (name?.errors?.['required']) {
              Name is required.
            }
            @if (name?.errors?.['minlength']) {
              Name must be at least 3 characters.
            }
          </div>
        }
      </div>

      <div class="form-group">
        <label class="checkbox-label">
          <input type="checkbox" formControlName="isPublic">
          Make playlist public
        </label>
      </div>

      <div class="form-actions">
        <button type="submit" class="submit-btn" [disabled]="playlistForm.invalid">
          Create Playlist
        </button>
        <a routerLink="/" class="cancel-btn">Cancel</a>
      </div>
    </form>
  }
</div>

// hw3/src/components/NewPlaylistForm.jsx
// src/components/NewPlaylistForm.jsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { usePlaylists } from '../hooks/usePlaylists';

const NewPlaylistForm = () => {
  const [playlistData, setPlaylistData] = useState({
    name: '',
    isPublic: false
  });
  const [error, setError] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const { addPlaylist } = usePlaylists();
  const navigate = useNavigate();

  const handleChange = (e) => {
    const { name, value, type, checked } = e.target;
    setPlaylistData(prev => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value
    }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    if (!playlistData.name.trim()) {
      setError('Playlist name is required');
      return;
    }
    
    setIsSubmitting(true);
    setError('');
    
    try {
      console.log('Submitting new playlist:', {
        name: playlistData.name,
        isPublic: playlistData.isPublic,
        tracks: []
      });
      
      const newPlaylist = await addPlaylist({
        name: playlistData.name,
        isPublic: playlistData.isPublic,
        tracks: []
      });
      
      console.log('Playlist created successfully:', newPlaylist);
      navigate('/');
    } catch (err) {
      console.error('Error creating playlist:', err);
      setError('Failed to create playlist. Please try again.');
      setIsSubmitting(false);
    }
  };

  return (
    <form onSubmit={handleSubmit} className="playlist-form">
      {error && <div className="error">{error}</div>}
      
      <div className="form-group">
        <label htmlFor="name">Playlist Name</label>
        <input
          type="text"
          id="name"
          name="name"
          value={playlistData.name}
          onChange={handleChange}
          required
        />
      </div>
      
      <div className="form-group checkbox">
        <label>
          <input
            type="checkbox"
            name="isPublic"
            checked={playlistData.isPublic}
            onChange={handleChange}
          />
          Make this playlist public
        </label>
      </div>
      
      <div className="form-actions">
        <button type="submit" disabled={isSubmitting}>
          {isSubmitting ? 'Creating...' : 'Create Playlist'}
        </button>
        <button 
          type="button" 
          onClick={() => navigate('/')}
          disabled={isSubmitting}
        >
          Cancel
        </button>
      </div>
    </form>
  );
};

export default NewPlaylistForm;
